# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/kisekis/.local/lib/python3.8/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/kisekis/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/EqualityChecker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/EqualityChecker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/kisekis/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/kisekis/.local/lib/python3.8/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/EqualityChecker/CMakeFiles /home/EqualityChecker//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/EqualityChecker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EqualityChecker

# Build rule for target.
EqualityChecker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EqualityChecker
.PHONY : EqualityChecker

# fast build rule for target.
EqualityChecker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/build
.PHONY : EqualityChecker/fast

controller.o: controller.cpp.o
.PHONY : controller.o

# target to build an object file
controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/controller.cpp.o
.PHONY : controller.cpp.o

controller.i: controller.cpp.i
.PHONY : controller.i

# target to preprocess a source file
controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/controller.cpp.i
.PHONY : controller.cpp.i

controller.s: controller.cpp.s
.PHONY : controller.s

# target to generate assembly for a file
controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/controller.cpp.s
.PHONY : controller.cpp.s

csv_writer.o: csv_writer.cpp.o
.PHONY : csv_writer.o

# target to build an object file
csv_writer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/csv_writer.cpp.o
.PHONY : csv_writer.cpp.o

csv_writer.i: csv_writer.cpp.i
.PHONY : csv_writer.i

# target to preprocess a source file
csv_writer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/csv_writer.cpp.i
.PHONY : csv_writer.cpp.i

csv_writer.s: csv_writer.cpp.s
.PHONY : csv_writer.s

# target to generate assembly for a file
csv_writer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/csv_writer.cpp.s
.PHONY : csv_writer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/main.cpp.s
.PHONY : main.cpp.s

processer.o: processer.cpp.o
.PHONY : processer.o

# target to build an object file
processer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/processer.cpp.o
.PHONY : processer.cpp.o

processer.i: processer.cpp.i
.PHONY : processer.i

# target to preprocess a source file
processer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/processer.cpp.i
.PHONY : processer.cpp.i

processer.s: processer.cpp.s
.PHONY : processer.s

# target to generate assembly for a file
processer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/processer.cpp.s
.PHONY : processer.cpp.s

source_code.o: source_code.cpp.o
.PHONY : source_code.o

# target to build an object file
source_code.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/source_code.cpp.o
.PHONY : source_code.cpp.o

source_code.i: source_code.cpp.i
.PHONY : source_code.i

# target to preprocess a source file
source_code.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/source_code.cpp.i
.PHONY : source_code.cpp.i

source_code.s: source_code.cpp.s
.PHONY : source_code.s

# target to generate assembly for a file
source_code.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/source_code.cpp.s
.PHONY : source_code.cpp.s

source_code_reader.o: source_code_reader.cpp.o
.PHONY : source_code_reader.o

# target to build an object file
source_code_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/source_code_reader.cpp.o
.PHONY : source_code_reader.cpp.o

source_code_reader.i: source_code_reader.cpp.i
.PHONY : source_code_reader.i

# target to preprocess a source file
source_code_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/source_code_reader.cpp.i
.PHONY : source_code_reader.cpp.i

source_code_reader.s: source_code_reader.cpp.s
.PHONY : source_code_reader.s

# target to generate assembly for a file
source_code_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EqualityChecker.dir/build.make CMakeFiles/EqualityChecker.dir/source_code_reader.cpp.s
.PHONY : source_code_reader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... EqualityChecker"
	@echo "... controller.o"
	@echo "... controller.i"
	@echo "... controller.s"
	@echo "... csv_writer.o"
	@echo "... csv_writer.i"
	@echo "... csv_writer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... processer.o"
	@echo "... processer.i"
	@echo "... processer.s"
	@echo "... source_code.o"
	@echo "... source_code.i"
	@echo "... source_code.s"
	@echo "... source_code_reader.o"
	@echo "... source_code_reader.i"
	@echo "... source_code_reader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

